### ISSUE TITLE
Checklist of tasks for post-CRAN acceptance

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/micronutr#35]
* [x] Accepted
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `git push`
* [x] Finish blog post, share on social media, etc.
* [x] Add link to blog post in `pkgdown` news menu
